Add logo svg
0xkalvin/fortunator pull request #42
Opened 2020-09-18 03:15 UTC by KaiqueJuvencio

## Descrição

Adiciona a logo com animação em todas as telas e também adiciona tela de feedback para quando o usuário é cadastrado com sucesso.

Resolve #41

2020-09-18 03:36 UTC, 0xkalvin requested changes

2020-09-18 03:36 UTC, 0xkalvin commented on frontend/.env
> +REACT_APP_VAR_TESTE=localhost:8989
Por que isso está sendo adicionado ? E o nome está misturando inglês com português também.

2020-09-18 03:37 UTC, 0xkalvin commented on frontend/local.Dockerfile
> +RUN echo -e "REACT_APP_API_URL=https//default.dev.api.com" >> .env
Por que isso está sendo adicionado aqui também ?

2020-09-18 03:39 UTC, 0xkalvin reviewed
Acredito que esse PR está adicionando/alterando muitas coisas ao mesmo tempo, sendo que pelo título do PR dá a entender que ele apenas adiciona um logo :joy: 

O que acha de quebrar esse PR em PRs menores ?

2020-09-19 01:43 UTC, 0xkalvin approved these changes

2020-09-19 01:47 UTC, wkinho approved these changes

2020-09-19 16:58 UTC, merged