Front register transaction
0xkalvin/fortunator pull request #75
Opened 2020-10-17 18:08 UTC by KaiqueJuvencio

## Descrição

Tela de criação de transações e categoria

Resolve #73

2020-10-17 20:00 UTC, 0xkalvin requested changes

2020-10-17 20:00 UTC, 0xkalvin commented on frontend/package-lock.json
> +{
Já estamos usando o `yarn.lock`,então não precisamos usar o `package-lock.json` :D

2020-10-19 22:29 UTC, 0xkalvin approved these changes

2020-10-19 22:30 UTC, wkinho approved these changes

2020-10-19 22:30 UTC, merged